provider "aws" {
  region = "${var.aws_region}"
}

# 1 ######### VPC ###########
resource "aws_vpc" "terraform-vpc" {
  cidr_block = "${var.vpc_entire_cidr}"

  #### this 2 true values are for use the internal vpc dns resolution
  enable_dns_support   = true
  enable_dns_hostnames = true

  tags {
    Name = "Generated by Terraform - VPC for LAMP stack"
  }
}
